// <auto-generated />
using System;
using MeetupPlanner.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetupPlanner.Migrations
{
    [DbContext(typeof(MeetupPlannerDbContext))]
    partial class MeetupPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Meetup", b =>
                {
                    b.Property<Guid>("MeetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AttendanceCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RsvpNoCount")
                        .HasColumnType("int");

                    b.Property<int?>("RsvpWaitlistCount")
                        .HasColumnType("int");

                    b.Property<int?>("RsvpYesCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalSpots")
                        .HasColumnType("int");

                    b.HasKey("MeetupId");

                    b.HasIndex("LocationId");

                    b.ToTable("Meetups");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.MeetupSpeaker", b =>
                {
                    b.Property<Guid>("MeetupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpeakerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeetupId", "SpeakerId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("MeetupSpeakers");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Presentation", b =>
                {
                    b.Property<Guid>("PresentationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlidesUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PresentationId");

                    b.ToTable("Presentations");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.PresentationSpeakerEntity", b =>
                {
                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpeakerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("PresentationId", "SpeakerId");

                    b.HasIndex("PresentationId")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("SpeakerId");

                    b.ToTable("PresentationSpeakers");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.ScheduleSlot", b =>
                {
                    b.Property<Guid>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MeetupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotId");

                    b.HasIndex("PresentationId");

                    b.HasIndex("MeetupId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ScheduleSlots");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Speaker", b =>
                {
                    b.Property<Guid>("SpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlogUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers", t =>
                        {
                            t.HasTrigger("TR_Speaker_Delete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.SpeakerBio", b =>
                {
                    b.Property<Guid>("SpeakerBioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpeakerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerBioId");

                    b.HasIndex("SpeakerId")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("SpeakerBios");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Meetup", b =>
                {
                    b.HasOne("MeetupPlanner.Infrastructure.Models.Location", "Location")
                        .WithMany("Meetups")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.MeetupSpeaker", b =>
                {
                    b.HasOne("MeetupPlanner.Infrastructure.Models.Meetup", "Meetup")
                        .WithMany("MeetupSpeakers")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetupPlanner.Infrastructure.Models.Speaker", "Speaker")
                        .WithMany("MeetupSpeakers")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meetup");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.PresentationSpeakerEntity", b =>
                {
                    b.HasOne("MeetupPlanner.Infrastructure.Models.Presentation", "Presentation")
                        .WithMany("PresentationSpeakers")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetupPlanner.Infrastructure.Models.Speaker", "Speaker")
                        .WithMany("PresentationSpeakers")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.ScheduleSlot", b =>
                {
                    b.HasOne("MeetupPlanner.Infrastructure.Models.Meetup", "Meetup")
                        .WithMany("ScheduleSlots")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetupPlanner.Infrastructure.Models.Presentation", "Presentation")
                        .WithMany("ScheduleSlots")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Meetup");

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.SpeakerBio", b =>
                {
                    b.HasOne("MeetupPlanner.Infrastructure.Models.Speaker", "Speaker")
                        .WithMany("Bios")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Location", b =>
                {
                    b.Navigation("Meetups");
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Meetup", b =>
                {
                    b.Navigation("MeetupSpeakers");

                    b.Navigation("ScheduleSlots");
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Presentation", b =>
                {
                    b.Navigation("PresentationSpeakers");

                    b.Navigation("ScheduleSlots");
                });

            modelBuilder.Entity("MeetupPlanner.Infrastructure.Models.Speaker", b =>
                {
                    b.Navigation("Bios");

                    b.Navigation("MeetupSpeakers");

                    b.Navigation("PresentationSpeakers");
                });
#pragma warning restore 612, 618
        }
    }
}
